# ETAPA 1: Construcción (Build)
# Usamos Node para instalar las librerías y compilar el código de React
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

# ETAPA 2: Servidor de Producción (Nginx)
# Una vez compilado, solo necesitamos un servidor web ligero para entregar los archivos
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]